### ISSUE TITLE
ComfyUI 0.33.1 regression: _encode_ref_audio moved back to MiniMaxH3ReferenceToVideo

### ISSUE THREAD

**Issue by jnsfhrmnn** [kat3ri/ComfyUI-MiniMax-H3-Extend#3]
## Summary

`MiniMaxH3VideoExtendPatched` crashes on current stock ComfyUI 0.33.1 whenever `ref_images` (or any other reference input) is connected:

```text
AttributeError: module 'comfy_extras.nodes_minimax_h3' has no attribute '_encode_ref_audio'
```

This is a forward-compatibility regression after #1 / commit `c4499cd`. That change was appropriate for the reported ComfyUI 0.33.0 layout, but ComfyUI 0.33.1 exposes the helper as `MiniMaxH3ReferenceToVideo._encode_ref_audio` instead of a module-level function.

## Environment

- ComfyUI: 0.33.1
- ComfyUI-MiniMax-H3-Extend: current `main` at `d175f0a`
- Python: 3.12.10 embedded
- PyTorch: 2.10.0+cu130
- OS: Windows 11
- GPU: NVIDIA GeForce RTX 5090

## Reproduction

1. Add `MiniMaxH3VideoExtendPatched`.
2. Connect the required `clip`, `vae`, `context_latent`, `prompt`, and `length` inputs.
3. Connect an image to `ref_images` (image-only reproduction; no reference audio is required).
4. Queue the workflow.

The lookup at `nodes.py:85` happens at the start of `_build_ref_blocks`, before the per-reference branches, so image-only references also trigger the audio-helper lookup and crash.

## Traceback tail

```text
File "custom_nodes/minimax-h3-extend/nodes.py", line 171, in _execute
    ref_items, ref_blocks = _build_ref_blocks(...)
File "custom_nodes/minimax-h3-extend/nodes.py", line 85, in _build_ref_blocks
    encode_ref_audio = native._encode_ref_audio
AttributeError: module 'comfy_extras.nodes_minimax_h3' has no attribute '_encode_ref_audio'
```

## Current ComfyUI 0.33.1 layout

In `comfy_extras/nodes_minimax_h3.py`, the helper is defined on the reference node class:

```python
class MiniMaxH3ReferenceToVideo(io.ComfyNode):
    @staticmethod
    def _encode_ref_audio(audio_vae, audio):
        ...
```

## Suggested compatibility lookup

Please support both layouts rather than selecting only one:

```python
encode_ref_audio = getattr(native, "_encode_ref_audio", None)
if encode_ref_audio is None:
    encode_ref_audio = native.MiniMaxH3ReferenceToVideo._encode_ref_audio
```

This keeps the 0.33.0 module-level path from #1 while also supporting the 0.33.1 class-level path. The fallback must be two-step; using the class attribute as the default argument to `getattr()` would evaluate it eagerly and could still fail on versions where that class attribute does not exist.

No ComfyUI downgrade or local direct patch of the custom node was applied; this report is from the unmodified upstream `main` code.

**Comment by kat3ri** [comment]
Thanks! Fixed in #12 with the two-step lookup you suggested: module level first (0.34+), then the `MiniMaxH3ReferenceToVideo` staticmethod (0.33.x).
