### PR TITLE
Fix reference-audio helper lookup across ComfyUI 0.33.0/0.33.1

### LINKED ISSUE #3: ComfyUI 0.33.1 regression: _encode_ref_audio moved back to MiniMaxH3ReferenceToVideo
## Summary

`MiniMaxH3VideoExtendPatched` crashes on current stock ComfyUI 0.33.1 whenever `ref_images` (or any other reference input) is connected:

```text
AttributeError: module 'comfy_extras.nodes_minimax_h3' has no attribute '_encode_ref_audio'
```

This is a forward-compatibility regression after #1 / commit `c4499cd`. That change was appropriate for the reported ComfyUI 0.33.0 layout, but ComfyUI 0.33.1 exposes the helper as `MiniMaxH3ReferenceToVideo._encode_ref_audio` instead of a module-level function.

## Environment

- ComfyUI: 0.33.1
- ComfyUI-MiniMax-H3-Extend: current `main` at `d175f0a`
- Python: 3.12.10 embedded
- PyTorch: 2.10.0+cu130
- OS: Windows 11
- GPU: NVIDIA GeForce RTX 5090

## Reproduction

1. Add `MiniMaxH3VideoExtendPatched`.
2. Connect the required `clip`, `vae`, `context_latent`, `prompt`, and `length` inputs.
3. Connect an image to `ref_images` (image-only reproduction; no reference audio is required).
4. Queue the workflow.

The lookup at `nodes.py:85` happens at the start of `_build_ref_blocks`, before the per-reference branches, so image-only references also trigger the audio-helper lookup and crash.

## Traceback tail

```text
File "custom_nodes/minimax-h3-extend/nodes.py", line 171, in _execute
    ref_items, ref_blocks = _build_ref_blocks(...)
File "custom_nodes/minimax-h3-extend/nodes.py", line 85, in _build_ref_blocks
    encode_ref_audio = native._encode_ref_audio
AttributeError: module 'comfy_extras.nodes_minimax_h3' has no attribute '_encode_ref_audio'
```

## Current ComfyUI 0.33.1 layout

In `comfy_extras/nodes_minimax_h3.py`, the helper is defined on the reference node class:

```python
class MiniMaxH3ReferenceToVideo(io.ComfyNode):
    @staticmethod
    def _encode_ref_audio(audio_vae, audio):
        ...
```

## Suggested compatibility lookup

Please support both layouts rather than selecting only one:

```python
encode_ref_audio = getattr(native, "_encode_ref_audio", None)
if encode_ref_audio is None:
    encode_ref_audio = native.MiniMaxH3ReferenceToVideo._encode_ref_audio
```

This keeps the 0.33.0 module-level path from #1 while also supporting the 0.33.1 class-level path. The fallback must be two-step; using the class attribute as the default argument to `getattr()` would evaluate it eagerly and could still fail on versions where that class attribute does not exist.

No ComfyUI downgrade or local direct patch of the custom node was applied; this report is from the unmodified upstream `main` code.

### PR DESCRIPTION
**Pull request by jnsfhrmnn**
## Summary

- resolve `_encode_ref_audio` lazily across both known stock ComfyUI layouts
- keep the module-level helper used by ComfyUI 0.33.0 and fall back to `MiniMaxH3ReferenceToVideo._encode_ref_audio` used by 0.33.1
- fail with an actionable compatibility error if neither helper exists
- add regression coverage for both layouts and for the image-only reference path that triggered the real crash

Fixes #3.

## Why the fallback is two-step

Using the class attribute directly as `getattr()`'s default would evaluate it eagerly. That still breaks ComfyUI versions where the module-level helper exists but the class-level helper does not. The resolver therefore checks each layout separately and accepts only callable helpers.

## Tests

```text
E:\ComfyUI7\python_embeded\python.exe -s -m unittest discover -s tests -v
Ran 5 tests in 0.001s — OK

E:\ComfyUI7\python_embeded\python.exe -s -m py_compile nodes.py tests\test_audio_helper_compat.py
git diff --check
```

The resolver was also loaded against an actual stock ComfyUI 0.33.1 installation and returned `MiniMaxH3ReferenceToVideo._encode_ref_audio`.

### CODE REVIEW

**Comment by jnsfhrmnn** [comment]
Additional integration verification against the actual stock ComfyUI 0.33.1 core:

- loaded this PR's `nodes.py` in the embedded ComfyUI Python with `-s`
- imported the real `comfy_extras.nodes_minimax_h3`
- executed `_build_ref_blocks` with an image-only reference and a lightweight fake VAE
- result: one image reference item and one `kind=image` block; no helper lookup exception

The installed custom-node copy remained unchanged during this verification.

**Comment by benjiyaya** [comment]
confirming the regression is real, and this PR's approach is the right one.
I've verified the helper's layout across stock ComfyUI versions:
- 0.33.0: module-level `_encode_ref_audio` (what #1 targeted; no class attribute)
- 0.33.1: `MiniMaxH3ReferenceToVideo._encode_ref_audio` staticmethod, no module-level
  function — merged `main` crashes there exactly as #3 reports
- 0.34.0 / current master: module-level again (I'm running 0.34.0 locally now and
  current `main` works fine on it)
So both layouts are live in the wild depending on version, and either single-layout
hardcode will keep breaking someone. The two-step lazy resolution here is correct —
the naive `getattr(native, "_encode_ref_audio", native.MiniMaxH3ReferenceToVideo._encode_ref_audio)`
form would evaluate the class attribute eagerly and crash on 0.33.0/0.34.0. The
callable checks and the actionable error naming both expected locations look good too.
Only note: `main` works as-is on 0.34.0 (tested, image-only refs, no crash), so this
isn't urgent for current users — but it's the right forward-compatibility hardening.
Changes exactly the one line #1 touched, no conflicts. LGTM.
